'use strict';
const auth=require('../lib/auth'),{query}=require('../lib/db'),{json,fail,readJson}=require('../lib/http');
const contacts={forma:{name:'Бородкина Мария',phone:'+79125905009',telegram:'KolsharaLoshara'},uyut:null,molod:null};
module.exports=function(route){
 async function context(req,res){const s=auth.readSession(req);if(!s){fail(res,401,'Не выполнен вход');return null;}const r=await query(`SELECT u.role,u.phone,p.place FROM users u LEFT JOIN staff_profiles p ON p.user_id=u.id WHERE u.id=$1 AND u.is_active`,[s.uid]);if(!r.rows[0]){fail(res,401,'Учётная запись отключена');return null;}return {...s,...r.rows[0]};}
 function all(s){return ['admin','moderator'].includes(s.role);}
 function scope(s,residence){return all(s)||(s.role==='staff' && (s.place===residence||contacts[residence]?.phone===s.phone));}
 async function current(uid){const r=await query(`SELECT r.residence_id FROM bookings b JOIN beds bd ON bd.id=b.bed_id JOIN rooms r ON r.id=bd.room_id WHERE b.user_id=$1 ORDER BY (b.date_from<=CURRENT_DATE AND b.date_to>=CURRENT_DATE) DESC,b.date_from DESC LIMIT 1`,[uid]);return r.rows[0]?.residence_id;}
 route('GET','/api/support',async(req,res)=>{const s=await context(req,res);if(!s)return;const residence=s.role==='resident'?await current(s.uid):String(req.query.residence||'forma');if(!residence)return json(res,200,{residence:null,contact:null,threads:[]});if(s.role!=='resident'&&!scope(s,residence))return fail(res,403,'Нет доступа к поддержке этой резиденции');
 let contact=contacts[residence]||null;if(contact){const photo=await query("SELECT photo_url FROM users WHERE regexp_replace(phone,'[^0-9]','','g')=$1 AND is_active LIMIT 1",[contact.phone.replace(/\D/g,'')]);contact={...contact,photo:photo.rows[0]?.photo_url||''};}
 const r=await query(`SELECT t.*,u.name FROM support_threads t JOIN users u ON u.id=t.user_id WHERE t.residence_id=$1 AND ($2::bigint IS NULL OR t.user_id=$2) ORDER BY t.updated_at DESC`,[residence,s.role==='resident'?s.uid:null]);const messages=await query('SELECT * FROM support_messages WHERE thread_id=ANY($1::bigint[]) ORDER BY id',[r.rows.map(x=>x.id)]);json(res,200,{residence,contact,threads:r.rows.map(t=>({...t,messages:messages.rows.filter(m=>m.thread_id===t.id)}))});
 });
 route('POST','/api/support',async(req,res)=>{const s=await context(req,res);if(!s)return;if(s.role!=='resident')return fail(res,403,'Обращение создаёт резидент');const b=await readJson(req),text=String(b.text||'').trim(),residence=await current(s.uid);if(!text||text.length>3000||!residence)return fail(res,400,'Нужны резиденция и текст до 3000 символов');const r=await query('INSERT INTO support_threads(user_id,residence_id,text) VALUES($1,$2,$3) RETURNING id',[s.uid,residence,text]);json(res,201,r.rows[0]);});
 route('POST','/api/support/:id/reply',async(req,res)=>{const s=await context(req,res);if(!s)return;const b=await readJson(req),text=String(b.text||'').trim();if(!text||text.length>3000)return fail(res,400,'Введите ответ до 3000 символов');const t=(await query('SELECT * FROM support_threads WHERE id=$1',[req.params.id])).rows[0];if(!t)return fail(res,404,'Обращение не найдено');if(!(s.role==='resident'?String(t.user_id)===String(s.uid):scope(s,t.residence_id)))return fail(res,403,'Нет доступа');await query('INSERT INTO support_messages(thread_id,author_id,text) VALUES($1,$2,$3)',[t.id,s.uid,text]);await query('UPDATE support_threads SET updated_at=now() WHERE id=$1',[t.id]);json(res,201,{ok:true});});
};
