'use strict';
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1400,height:950}});let saved=null;const errors=[];page.on('pageerror',e=>errors.push(e.message));
const people=[{id:'1',userId:'1',name:'Проверка Владелец',role:'admin',position:'Администратор 1',place:'all',sectionAccess:{chart:true,residents:true,tickets:true,charges:true,payroll:true}},{id:'2',userId:'2',name:'Проверка Модератор',role:'moderator',position:'Модератор',place:'forma',salary:30000,started:'2026-01-01',sectionAccess:{chart:true,residents:true,tickets:true,charges:true,payroll:false}}];
await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname.startsWith('/api/')){
if(u.pathname==='/api/auth/me')return route.fulfill({json:{id:'1',role:'admin',name:'Проверка Владелец',canEditSite:true,canPayroll:true,sectionAccess:people[0].sectionAccess}});
if(u.pathname==='/api/staff')return route.fulfill({json:people});
if(u.pathname.endsWith('/sections')){saved=route.request().postDataJSON();return route.fulfill({json:{ok:true}});}
if(u.pathname==='/api/content/meta')return route.fulfill({json:{count:0}});
return route.fulfill({json:[]});}
const file=path.join('web',u.pathname.slice(1));return fs.existsSync(file)&&fs.statSync(file).isFile()?route.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'application/octet-stream'}):route.fulfill({status:404,body:''});});
await page.goto('https://msv.test/admin-rights.html');await page.locator('[data-act="edit"][data-id="2"]').click();await page.locator('[data-p="Шахматка"]').click();assert.equal(await page.locator('[data-p="Резиденты"]').getAttribute('aria-pressed'),'true');await page.locator('[data-act="save"]').click();await page.waitForFunction(()=>!document.querySelector('[data-act="save"]'));assert.equal(saved.chart,false);assert.equal(saved.residents,true);assert.equal(saved.role,undefined);console.log('PASS single section toggles without changing roles');
await page.goto('https://msv.test/admin-staff.html');await page.locator('#rows tr[data-id="2"]').waitFor();assert.equal(await page.locator('[data-bonus]').count(),2);await page.locator('[data-place="all"]').click();assert.equal(await page.locator('#rows tr[data-id]').count(),1);assert.match(await page.locator('#rows').innerText(),/Владелец/);await page.locator('[data-place=""]').click();await page.locator('th[data-sort="name"]').click();assert.match(await page.locator('#rows tr[data-id]').first().innerText(),/Модератор/);console.log('PASS staff administration filter, sorting, separate bonus button');
await page.goto('https://msv.test/contracts-preview.html');await page.locator('main:not([hidden])').waitFor();assert.equal(await page.locator('.grip').count(),0);assert.equal(await page.locator('table').first().locator('th').count(),13);await page.locator('#configure').click();assert(await page.locator('.grip').count()>0);await page.locator('.name').first().click();assert.equal(await page.locator('input[name="responsible"]').isEnabled(),true);await page.locator('#close').click();await page.screenshot({path:'.tmp/oct04-contracts.png'});console.log('PASS contract groups, 12 rolling months, gear editing and responsible/executor fields');
assert.deepEqual(errors,[]);console.log('PASS no browser exceptions');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
