'use strict';
const assert=require('node:assert/strict');
if(!String(process.env.DATABASE_URL).includes('msv_oct04_check'))throw Error('Only isolated msv_oct04_check database allowed');
const {query}=require('./lib/db'),auth=require('./lib/auth'),{server}=require('./index');
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
 async function user(role,phone,owner=false){const r=await query('INSERT INTO users(role,name,phone,can_edit_site) VALUES($1,$2,$3,$4) RETURNING *',[role,'Проверка Правок',phone,owner]);const u=r.rows[0];await query('UPDATE users SET pin_hash=$2 WHERE id=$1',[u.id,auth._internal.hashPin('4826',u.id)]);return {...u,cookie:auth.sessionCookie(u).split(';')[0]};}
 const owner=await user('admin','+79000000701',true),mod=await user('moderator','+79000000702'),staff=await user('staff','+79000000703'),resident=await user('resident','+79000000704');
 async function call(path,who,body,method){const r=await fetch(base+path,{method:method||(body?'POST':'GET'),headers:{...(who?{cookie:who.cookie}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};}
 const edit={page:'index.html',changes:[{key:'h1:0',html:'После',original:'До'}]};
 assert.equal((await call('/api/content',mod,edit)).status,403);
 assert.equal((await call('/api/content',owner,edit)).status,200);
 let history=await call('/api/content/history',owner);assert.equal(history.body[0].before_html,'До');const id=history.body[0].id;
 assert.equal((await call('/api/content/history/'+id+'/restore',owner,{version:'before'})).status,200);
 assert.equal((await call('/api/content?page=index.html')).body[0].html,'До');
 assert.equal((await call('/api/content/history',resident)).status,403);
 console.log('PASS content history, individual restore, owner-only writes');
 for(let i=1;i<=4;i++){const r=await call('/api/auth/verify-pin',null,{contact:resident.phone,pin:'9876'});assert.equal(r.body.attemptsRemaining,4-i);if(i===4){assert.equal(r.status,429);assert(r.body.lockedUntil);}}
 assert.equal((await call('/api/auth/verify-pin',null,{contact:resident.phone,pin:'4826'})).status,429);
 await query("UPDATE users SET locked_until=now()-interval '1 second' WHERE id=$1",[resident.id]);
 assert.equal((await call('/api/auth/verify-pin',null,{contact:resident.phone,pin:'9876'})).body.attemptsRemaining,3);
 assert.equal((await call('/api/auth/verify-pin',null,{contact:resident.phone,pin:'4826'})).status,200);
 console.log('PASS PIN countdown data, four failures, enforced lock, reset after expiry');
 assert.equal((await call('/api/me/profile',resident,{firstName:'Alex'},'PUT')).status,400);
 assert.equal((await call('/api/staff/'+staff.id+'/sections',mod,{chart:false},'PUT')).status,403);
 assert.equal((await call('/api/staff/'+mod.id+'/sections',owner,{chart:false,residents:true,charges:false},'PUT')).status,200);
 assert.equal((await call('/api/holds',mod,{hours:24})).status,403);
 assert.equal((await call('/api/payments',mod,{bookingId:1,amount:100})).status,403);
 const me=await call('/api/auth/me',mod);assert.equal(me.body.sectionAccess.chart,false);assert.equal(me.body.sectionAccess.residents,true);assert.equal(me.body.canEditShahmatka,false);
 assert.equal((await call('/api/payroll',owner,{userId:staff.id,period:'Проверка премии',amount:0,bonus:500})).status,201);
 console.log('PASS independent permissions, backend denial, names, standalone bonus');
 const versions=require('./lib/document-versions'),v1=await versions.snapshot(query,'contract');
 await query("INSERT INTO content_overrides(page,key,html,updated_by) VALUES('doc-contract.html','p:0','Новая редакция',$1)",[owner.id]);
 const v2=await versions.snapshot(query,'contract');assert.notEqual(String(v1),String(v2));
 const old=(await query('SELECT overrides FROM document_versions WHERE id=$1',[v1])).rows[0];assert.equal(old.overrides.length,0);
 assert.equal((await call('/api/me/document-versions/'+v1,resident)).status,404);
 console.log('PASS immutable document snapshots and access control');
 await query("INSERT INTO residences(id,name,title) VALUES('forma','FORMA','FORMA'),('uyut','Уют','Уют')");
 await query("INSERT INTO rooms(id,residence_id,number,name,size) VALUES('test-room','forma','1','Проверка',1)");
 await query("INSERT INTO beds(id,room_id,label,price) VALUES('test-bed','test-room','1',100)");
 await query("INSERT INTO bookings(user_id,bed_id,date_from,date_to) VALUES($1,'test-bed',CURRENT_DATE-1,CURRENT_DATE+30)",[resident.id]);
 const ticket=await call('/api/support',resident,{text:'Тест поддержки'});assert.equal(ticket.status,201);
 assert.equal((await call('/api/support',resident)).body.contact.name,'Бородкина Мария');
 assert.equal((await call('/api/support?residence=uyut',owner)).body.threads.length,0);
 assert.equal((await call('/api/support?residence=forma',owner)).body.threads.length,1);
 assert.equal((await call('/api/support?residence=forma',staff)).status,403);
 assert.equal((await call('/api/support/'+ticket.body.id+'/reply',owner,{text:'Ответ'})).status,201);
 assert.equal((await call('/api/support',resident)).body.threads[0].messages.length,1);
 console.log('PASS support residence isolation, contact routing and replies');
 const departure={kind:'departure',date:'2027-07-20',reason:'Переезд',residenceRating:5,staffRating:4,comments:'Спасибо'};
 assert.equal((await call('/api/requests',resident,{...departure,staffRating:6})).status,400);
 assert.equal((await call('/api/requests',resident,departure)).status,201);
 assert.equal((await call('/api/requests/inbox',owner)).body.length,1);
 assert.equal((await call('/api/requests/inbox',resident)).status,403);
 assert.equal((await query('SELECT count(*)::int n FROM bookings')).rows[0].n,1);
 assert.equal((await call('/api/content',owner,{page:'cabinet-admin.html',changes:[{key:'menu:cabinet-admin.html',html:'Обзор',original:'Статистика'}]})).status,200);
 assert((await call('/api/content?page=admin-residents.html')).body.some(x=>x.key==='menu:cabinet-admin.html'&&x.html==='Обзор'));
 console.log('PASS departure validation, staff inbox, unchanged booking, shared menu labels');
 const current=await call('/api/documents/current');assert.equal(current.status,200);
 await query("INSERT INTO beds(id,room_id,label,price) VALUES('test-bed-sign','test-room','2',100)");
 const booking={bedId:'test-bed-sign',from:'2027-01-01',to:'2027-08-31',docs:{contract:true,rules:true,consent:true},docVersions:current.body};
 const before=(await query('SELECT count(*)::int n FROM bookings')).rows[0].n;
 assert.equal((await call('/api/bookings',resident,{...booking,docVersions:{...current.body,contract:'0'}})).status,409);
 assert.equal((await query('SELECT count(*)::int n FROM bookings')).rows[0].n,before);
 assert.equal((await call('/api/bookings',resident,booking)).status,201);
 assert.equal((await call('/api/me/document-versions/'+current.body.contract,resident)).status,200);
 console.log('PASS stale document rejection rolls back booking, current signatures retain edition');
 console.log('ALL OCT04 INTEGRATION CHECKS PASSED');
})().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});
