(async function(){
 const box=document.getElementById('departure');try{
 const response=await fetch('/api/auth/me',{credentials:'same-origin'});if(!response.ok){box.textContent='Для подачи заявки войдите в кабинет.';return;}const me=await response.json();
 if(me.role!=='resident'){const r=await fetch('/api/requests/inbox',{credentials:'same-origin'}),list=await r.json();if(!r.ok)throw Error(list.error);if(!list.length)box.textContent='Заявок на выезд пока нет.';list.forEach(x=>{const section=document.createElement('section');section.style.cssText='padding:16px;background:white;margin-bottom:16px;border-radius:12px';const name=document.createElement('a');name.href='resident-card.html?id='+x.user_id;name.textContent=x.name;const p=document.createElement('p');p.style.whiteSpace='pre-wrap';p.textContent=x.note;section.append(name,p);box.append(section);});return;}
 const form=document.createElement('form');form.innerHTML='<p>Укажите планируемую дату выезда. Заявку рассмотрит администрация.</p><label class="msv-field">Дата выезда<input class="msv-input" name="date" type="date" required></label><label class="msv-field">Причина выезда<textarea class="msv-area" name="reason" required maxlength="1000"></textarea></label>';
 ['residence','staff'].forEach(key=>{const field=document.createElement('fieldset');field.style.cssText='border:0;padding:0;margin:16px 0';const legend=document.createElement('legend');legend.textContent=key==='residence'?'Оцените резиденцию':'Оцените сотрудников';field.append(legend);for(let i=1;i<=5;i++){const label=document.createElement('label');label.style.cssText='display:inline-flex;align-items:center;margin:8px';const input=document.createElement('input');input.type='radio';input.name=key;input.value=i;input.required=true;label.append(input,' '+i+' ★');field.append(label);}form.append(field);});
 const comments=document.createElement('textarea');comments.className='msv-area';comments.name='comments';comments.placeholder='Поясните ваши оценки';comments.maxLength=1000;form.append(comments);const status=document.createElement('p');status.setAttribute('role','status');const button=document.createElement('button');button.className='msv-btn msv-btn--primary';button.textContent='Подать заявку';form.append(status,button);box.append(form);
 form.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{const f=Object.fromEntries(new FormData(form));const r=await fetch('/api/requests',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'departure',date:f.date,reason:f.reason,residenceRating:Number(f.residence),staffRating:Number(f.staff),comments:f.comments})}),j=await r.json();if(!r.ok)throw Error(j.error);form.replaceChildren();const p=document.createElement('p');p.textContent='Заявка на выезд принята. Дата: '+f.date.split('-').reverse().join('.')+'.';form.append(p);}catch(e){status.textContent=e.message;button.disabled=false;}};
 }catch(e){box.textContent=e.message;}
})();
