/* © 2026 МСВ. Все права защищены. Программа для ЭВМ охраняется ст. 1259, 1261 ГК РФ. Использование без разрешения правообладателя запрещено. Подробнее: /legal.html */
/* ============================================================
   МСВ — резиденции, комнаты и места
   Данные заказчика. Цены — за месяц при годовом контракте.

   Три места, где в исходном списке не хватает сведений:

   1. Уют — структура сверена с реальным заселением (файл от 14.09.2026):
      №12 «Сочи» — 12 капсул; №1, №2, №3 — по 6 мест (четыре основных
      и два дополнительных, в №3 — в гостиной). Цена дополнительных
      мест принята как у основных — уточните.
   2. FORMA, комнаты №6 «Булгаков», №11 «Цой», №14 «Бродский» —
      пол не указан. Оставлено пустым: в шахматке метка не показывается.
   3. Молодежка, комнаты №2 и №3 — места равноценные, без деления
      на верхнее и нижнее. Так и записаны.

   Уют, комната №5 — для персонала, в базу не внесена.
   ============================================================ */

window.MSV_RESIDENCES = [
  {
    id: "forma", name: "FORMA", title: "Резиденция FORMA", logo: "forma.png",
    rooms: [
      {"id": "forma-r1", "buildingId": "forma", "number": "1", "name": "№1 Рерих", "gender": "м", "size": 4, "note": "со своим санузлом и душем"},
      {"id": "forma-r2", "buildingId": "forma", "number": "2", "name": "№2 Билибин", "gender": "м", "size": 4, "note": "со своим санузлом и душем"},
      {"id": "forma-r3", "buildingId": "forma", "number": "3", "name": "№3 Шостакович", "gender": "м", "size": 4, "note": "со своим санузлом и душем"},
      {"id": "forma-r4", "buildingId": "forma", "number": "4", "name": "№4 Чуковский", "gender": "ж", "size": 4, "note": "со своим санузлом и душем"},
      {"id": "forma-r5", "buildingId": "forma", "number": "5", "name": "№5 Капица", "gender": "м", "size": 2, "note": ""},
      {"id": "forma-r6", "buildingId": "forma", "number": "6", "name": "№6 Булгаков", "gender": "ж", "size": 1, "note": "одноместная"},
      {"id": "forma-r7", "buildingId": "forma", "number": "7", "name": "№7 Блаватская", "gender": "ж", "size": 2, "note": ""},
      {"id": "forma-r8", "buildingId": "forma", "number": "8", "name": "№8 Менделеев", "gender": "ж", "size": 4, "note": ""},
      {"id": "forma-r9", "buildingId": "forma", "number": "9", "name": "№9 Тарковский", "gender": "ж", "size": 2, "note": "окно в коридор"},
      {"id": "forma-r10", "buildingId": "forma", "number": "10", "name": "№10 Цветаева", "gender": "ж", "size": 8, "note": ""},
      {"id": "forma-r11", "buildingId": "forma", "number": "11", "name": "№11 Цой", "gender": "ж", "size": 1, "note": "одноместная"},
      {"id": "forma-r12", "buildingId": "forma", "number": "12", "name": "№12 Рублев", "gender": "ж", "size": 4, "note": ""},
      {"id": "forma-r13", "buildingId": "forma", "number": "13", "name": "№13 Шухов", "gender": "м", "size": 8, "note": ""},
      {"id": "forma-r14", "buildingId": "forma", "number": "14", "name": "№14 Бродский", "gender": "ж", "size": 1, "note": "одноместная"},
      {"id": "forma-r15", "buildingId": "forma", "number": "15", "name": "№15 Королев", "gender": "м", "size": 4, "note": ""},
      {"id": "forma-r16", "buildingId": "forma", "number": "16", "name": "№16 Станиславский", "gender": "ж", "size": 4, "note": ""},
    ],
    beds: [
      {"id": "forma-b1-1", "roomId": "forma-r1", "label": "1.1.н", "tier": "нижнее", "price": 38170},
      {"id": "forma-b1-2", "roomId": "forma-r1", "label": "1.2.н", "tier": "нижнее", "price": 38170},
      {"id": "forma-b1-3", "roomId": "forma-r1", "label": "1.3.в", "tier": "верхнее", "price": 34100},
      {"id": "forma-b1-4", "roomId": "forma-r1", "label": "1.4.в", "tier": "верхнее", "price": 34100},
      {"id": "forma-b2-1", "roomId": "forma-r2", "label": "2.1.н", "tier": "нижнее", "price": 38170},
      {"id": "forma-b2-2", "roomId": "forma-r2", "label": "2.2.н", "tier": "нижнее", "price": 38170},
      {"id": "forma-b2-3", "roomId": "forma-r2", "label": "2.3.в", "tier": "верхнее", "price": 34100},
      {"id": "forma-b2-4", "roomId": "forma-r2", "label": "2.4.в", "tier": "верхнее", "price": 34100},
      {"id": "forma-b3-1", "roomId": "forma-r3", "label": "3.1.н", "tier": "нижнее", "price": 38170},
      {"id": "forma-b3-2", "roomId": "forma-r3", "label": "3.2.н", "tier": "нижнее", "price": 38170},
      {"id": "forma-b3-3", "roomId": "forma-r3", "label": "3.3.в", "tier": "верхнее", "price": 34100},
      {"id": "forma-b3-4", "roomId": "forma-r3", "label": "3.4.в", "tier": "верхнее", "price": 34100},
      {"id": "forma-b4-1", "roomId": "forma-r4", "label": "4.1.н", "tier": "нижнее", "price": 38170},
      {"id": "forma-b4-2", "roomId": "forma-r4", "label": "4.2.н", "tier": "нижнее", "price": 38170},
      {"id": "forma-b4-3", "roomId": "forma-r4", "label": "4.3.в", "tier": "верхнее", "price": 34100},
      {"id": "forma-b4-4", "roomId": "forma-r4", "label": "4.4.в", "tier": "верхнее", "price": 34100},
      {"id": "forma-b5-1", "roomId": "forma-r5", "label": "5.1.в", "tier": "верхнее", "price": 43700},
      {"id": "forma-b5-2", "roomId": "forma-r5", "label": "5.2.н", "tier": "нижнее", "price": 47750},
      {"id": "forma-b6-1", "roomId": "forma-r6", "label": "6.1", "tier": "", "price": 38500},
      {"id": "forma-b7-1", "roomId": "forma-r7", "label": "7.1.в", "tier": "верхнее", "price": 43700},
      {"id": "forma-b7-2", "roomId": "forma-r7", "label": "7.2.н", "tier": "нижнее", "price": 47750},
      {"id": "forma-b8-1", "roomId": "forma-r8", "label": "8.1.в", "tier": "верхнее", "price": 31350},
      {"id": "forma-b8-2", "roomId": "forma-r8", "label": "8.2.н", "tier": "нижнее", "price": 34100},
      {"id": "forma-b8-3", "roomId": "forma-r8", "label": "8.3.в", "tier": "верхнее", "price": 31350},
      {"id": "forma-b8-4", "roomId": "forma-r8", "label": "8.4.н", "tier": "нижнее", "price": 34100},
      {"id": "forma-b9-1", "roomId": "forma-r9", "label": "9.1.в", "tier": "верхнее", "price": 39050},
      {"id": "forma-b9-2", "roomId": "forma-r9", "label": "9.2.н", "tier": "нижнее", "price": 44350},
      {"id": "forma-b10-1", "roomId": "forma-r10", "label": "10.1.в", "tier": "верхнее", "price": 27280},
      {"id": "forma-b10-2", "roomId": "forma-r10", "label": "10.2.н", "tier": "нижнее", "price": 31350},
      {"id": "forma-b10-3", "roomId": "forma-r10", "label": "10.3.в", "tier": "верхнее", "price": 27280},
      {"id": "forma-b10-4", "roomId": "forma-r10", "label": "10.4.н", "tier": "нижнее", "price": 31350},
      {"id": "forma-b10-5", "roomId": "forma-r10", "label": "10.5.в", "tier": "верхнее", "price": 27280},
      {"id": "forma-b10-6", "roomId": "forma-r10", "label": "10.6.н", "tier": "нижнее", "price": 31350},
      {"id": "forma-b10-7", "roomId": "forma-r10", "label": "10.7.в", "tier": "верхнее", "price": 27280},
      {"id": "forma-b10-8", "roomId": "forma-r10", "label": "10.8.н", "tier": "нижнее", "price": 31350},
      {"id": "forma-b11-1", "roomId": "forma-r11", "label": "11.1", "tier": "", "price": 38500},
      {"id": "forma-b12-1", "roomId": "forma-r12", "label": "12.1.в", "tier": "верхнее", "price": 31350},
      {"id": "forma-b12-2", "roomId": "forma-r12", "label": "12.2.н", "tier": "нижнее", "price": 34100},
      {"id": "forma-b12-3", "roomId": "forma-r12", "label": "12.3.в", "tier": "верхнее", "price": 31350},
      {"id": "forma-b12-4", "roomId": "forma-r12", "label": "12.4.н", "tier": "нижнее", "price": 34100},
      {"id": "forma-b13-1", "roomId": "forma-r13", "label": "13.1.в", "tier": "верхнее", "price": 27280},
      {"id": "forma-b13-2", "roomId": "forma-r13", "label": "13.2.н", "tier": "нижнее", "price": 31350},
      {"id": "forma-b13-3", "roomId": "forma-r13", "label": "13.3.в", "tier": "верхнее", "price": 27280},
      {"id": "forma-b13-4", "roomId": "forma-r13", "label": "13.4.н", "tier": "нижнее", "price": 31350},
      {"id": "forma-b13-5", "roomId": "forma-r13", "label": "13.5.в", "tier": "верхнее", "price": 27280},
      {"id": "forma-b13-6", "roomId": "forma-r13", "label": "13.6.н", "tier": "нижнее", "price": 31350},
      {"id": "forma-b13-7", "roomId": "forma-r13", "label": "13.7.в", "tier": "верхнее", "price": 27280},
      {"id": "forma-b13-8", "roomId": "forma-r13", "label": "13.8.н", "tier": "нижнее", "price": 31350},
      {"id": "forma-b14-1", "roomId": "forma-r14", "label": "14.1", "tier": "", "price": 38500},
      {"id": "forma-b15-1", "roomId": "forma-r15", "label": "15.1.в", "tier": "верхнее", "price": 31350},
      {"id": "forma-b15-2", "roomId": "forma-r15", "label": "15.2.в", "tier": "верхнее", "price": 31350},
      {"id": "forma-b15-3", "roomId": "forma-r15", "label": "15.3.н", "tier": "нижнее", "price": 34100},
      {"id": "forma-b15-4", "roomId": "forma-r15", "label": "15.4.н", "tier": "нижнее", "price": 34100},
      {"id": "forma-b16-1", "roomId": "forma-r16", "label": "16.1.в", "tier": "верхнее", "price": 31350},
      {"id": "forma-b16-2", "roomId": "forma-r16", "label": "16.2.в", "tier": "верхнее", "price": 31350},
      {"id": "forma-b16-3", "roomId": "forma-r16", "label": "16.3.н", "tier": "нижнее", "price": 34100},
      {"id": "forma-b16-4", "roomId": "forma-r16", "label": "16.4.н", "tier": "нижнее", "price": 34100},
    ]
  },
  {
    id: "uyut", name: "Уют", title: "Резиденция Уют", logo: "uyt.gif",
    rooms: [
      {"id": "uyut-r1", "buildingId": "uyut", "number": "1", "name": "№1 Иваново", "gender": "ж", "size": 6, "note": "6 мест: четыре основных и два дополнительных"},
      {"id": "uyut-r2", "buildingId": "uyut", "number": "2", "name": "№2 Казань", "gender": "ж", "size": 6, "note": "6 мест: четыре основных и два дополнительных"},
      {"id": "uyut-r3", "buildingId": "uyut", "number": "3", "name": "№3 Ярославль", "gender": "м", "size": 6, "note": "6 мест: четыре основных и два в гостиной"},
      {"id": "uyut-r4", "buildingId": "uyut", "number": "4", "name": "№4 Екб", "gender": "ж", "size": 2, "note": ""},
      {"id": "uyut-r6", "buildingId": "uyut", "number": "6", "name": "№6 Ростов", "gender": "м", "size": 4, "note": ""},
      {"id": "uyut-r7", "buildingId": "uyut", "number": "7", "name": "№7 Воронеж", "gender": "м", "size": 4, "note": ""},
      {"id": "uyut-r8", "buildingId": "uyut", "number": "8", "name": "№8 Новосибирск", "gender": "ж", "size": 4, "note": ""},
      {"id": "uyut-r9", "buildingId": "uyut", "number": "9", "name": "№9 Красноярск", "gender": "ж", "size": 4, "note": ""},
      {"id": "uyut-r10", "buildingId": "uyut", "number": "10", "name": "№10 Камчатка", "gender": "м", "size": 2, "note": ""},
      {"id": "uyut-r11", "buildingId": "uyut", "number": "11", "name": "№11 Сахалин", "gender": "ж", "size": 6, "note": ""},
      {"id": "uyut-r12", "buildingId": "uyut", "number": "12", "name": "№12 Сочи", "gender": "м", "size": 12, "note": "капсулы"},
      {"id": "uyut-r13", "buildingId": "uyut", "number": "13", "name": "№13 Абакан", "gender": "м", "size": 4, "note": ""},
      {"id": "uyut-r14", "buildingId": "uyut", "number": "14", "name": "№14 Тула", "gender": "м", "size": 2, "note": ""},
      {"id": "uyut-r15", "buildingId": "uyut", "number": "15", "name": "№15 Питер", "gender": "м", "size": 4, "note": ""},
      {"id": "uyut-r16", "buildingId": "uyut", "number": "16", "name": "№16 Шереметьево", "gender": "м", "size": 8, "note": ""},
      {"id": "uyut-r17", "buildingId": "uyut", "number": "17", "name": "№17 Кострома", "gender": "м", "size": 4, "note": ""},
    ],
    beds: [
      {"id": "uyut-b1-1", "roomId": "uyut-r1", "label": "1.1.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b1-2", "roomId": "uyut-r1", "label": "1.2.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b1-3", "roomId": "uyut-r1", "label": "1.3.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b1-4", "roomId": "uyut-r1", "label": "1.4.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b1-5", "roomId": "uyut-r1", "label": "1.5.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b1-6", "roomId": "uyut-r1", "label": "1.6.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b2-1", "roomId": "uyut-r2", "label": "2.1", "tier": "", "price": 24200},
      {"id": "uyut-b2-2", "roomId": "uyut-r2", "label": "2.2", "tier": "", "price": 24200},
      {"id": "uyut-b2-3", "roomId": "uyut-r2", "label": "2.3.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b2-4", "roomId": "uyut-r2", "label": "2.4.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b2-5", "roomId": "uyut-r2", "label": "2.5", "tier": "", "price": 24200},
      {"id": "uyut-b2-6", "roomId": "uyut-r2", "label": "2.6", "tier": "", "price": 24200},
      {"id": "uyut-b3-1", "roomId": "uyut-r3", "label": "3.1", "tier": "", "price": 24200},
      {"id": "uyut-b3-2", "roomId": "uyut-r3", "label": "3.2", "tier": "", "price": 24200},
      {"id": "uyut-b3-3", "roomId": "uyut-r3", "label": "3.3.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b3-4", "roomId": "uyut-r3", "label": "3.4.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b3-5", "roomId": "uyut-r3", "label": "3.5", "tier": "", "price": 24200},
      {"id": "uyut-b3-6", "roomId": "uyut-r3", "label": "3.6", "tier": "", "price": 24200},
      {"id": "uyut-b4-1", "roomId": "uyut-r4", "label": "4.1.в", "tier": "верхнее", "price": 35200},
      {"id": "uyut-b4-2", "roomId": "uyut-r4", "label": "4.2.н", "tier": "нижнее", "price": 38500},
      {"id": "uyut-b6-1", "roomId": "uyut-r6", "label": "6.1.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b6-2", "roomId": "uyut-r6", "label": "6.2.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b6-3", "roomId": "uyut-r6", "label": "6.3.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b6-4", "roomId": "uyut-r6", "label": "6.4.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b7-1", "roomId": "uyut-r7", "label": "7.1.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b7-2", "roomId": "uyut-r7", "label": "7.2.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b7-3", "roomId": "uyut-r7", "label": "7.3.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b7-4", "roomId": "uyut-r7", "label": "7.4.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b8-1", "roomId": "uyut-r8", "label": "8.1.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b8-2", "roomId": "uyut-r8", "label": "8.2.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b8-3", "roomId": "uyut-r8", "label": "8.3.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b8-4", "roomId": "uyut-r8", "label": "8.4.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b9-1", "roomId": "uyut-r9", "label": "9.1.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b9-2", "roomId": "uyut-r9", "label": "9.2.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b9-3", "roomId": "uyut-r9", "label": "9.3.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b9-4", "roomId": "uyut-r9", "label": "9.4.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b10-1", "roomId": "uyut-r10", "label": "10.1.в", "tier": "верхнее", "price": 35200},
      {"id": "uyut-b10-2", "roomId": "uyut-r10", "label": "10.2.н", "tier": "нижнее", "price": 38500},
      {"id": "uyut-b11-1", "roomId": "uyut-r11", "label": "11.1.в", "tier": "верхнее", "price": 22000},
      {"id": "uyut-b11-2", "roomId": "uyut-r11", "label": "11.2.в", "tier": "верхнее", "price": 22000},
      {"id": "uyut-b11-3", "roomId": "uyut-r11", "label": "11.3.в", "tier": "верхнее", "price": 22000},
      {"id": "uyut-b11-4", "roomId": "uyut-r11", "label": "11.4.н", "tier": "нижнее", "price": 25300},
      {"id": "uyut-b11-5", "roomId": "uyut-r11", "label": "11.5.н", "tier": "нижнее", "price": 25300},
      {"id": "uyut-b11-6", "roomId": "uyut-r11", "label": "11.6.н", "tier": "нижнее", "price": 25300},
      {"id": "uyut-b12-1", "roomId": "uyut-r12", "label": "12.1.в", "tier": "верхнее", "price": 20900},
      {"id": "uyut-b12-2", "roomId": "uyut-r12", "label": "12.2.в", "tier": "верхнее", "price": 20900},
      {"id": "uyut-b12-3", "roomId": "uyut-r12", "label": "12.3.в", "tier": "верхнее", "price": 20900},
      {"id": "uyut-b12-4", "roomId": "uyut-r12", "label": "12.4.в", "tier": "верхнее", "price": 20900},
      {"id": "uyut-b12-5", "roomId": "uyut-r12", "label": "12.5.в", "tier": "верхнее", "price": 20900},
      {"id": "uyut-b12-6", "roomId": "uyut-r12", "label": "12.6.в", "tier": "верхнее", "price": 20900},
      {"id": "uyut-b12-7", "roomId": "uyut-r12", "label": "12.7.н", "tier": "нижнее", "price": 24200},
      {"id": "uyut-b12-8", "roomId": "uyut-r12", "label": "12.8.н", "tier": "нижнее", "price": 24200},
      {"id": "uyut-b12-9", "roomId": "uyut-r12", "label": "12.9.н", "tier": "нижнее", "price": 24200},
      {"id": "uyut-b12-10", "roomId": "uyut-r12", "label": "12.10.н", "tier": "нижнее", "price": 24200},
      {"id": "uyut-b12-11", "roomId": "uyut-r12", "label": "12.11.н", "tier": "нижнее", "price": 24200},
      {"id": "uyut-b12-12", "roomId": "uyut-r12", "label": "12.12.н", "tier": "нижнее", "price": 24200},
      {"id": "uyut-b13-1", "roomId": "uyut-r13", "label": "13.1.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b13-2", "roomId": "uyut-r13", "label": "13.2.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b13-3", "roomId": "uyut-r13", "label": "13.3.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b13-4", "roomId": "uyut-r13", "label": "13.4.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b14-1", "roomId": "uyut-r14", "label": "14.1.в", "tier": "верхнее", "price": 35200},
      {"id": "uyut-b14-2", "roomId": "uyut-r14", "label": "14.2.н", "tier": "нижнее", "price": 38500},
      {"id": "uyut-b15-1", "roomId": "uyut-r15", "label": "15.1.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b15-2", "roomId": "uyut-r15", "label": "15.2.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b15-3", "roomId": "uyut-r15", "label": "15.3.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b15-4", "roomId": "uyut-r15", "label": "15.4.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b16-1", "roomId": "uyut-r16", "label": "16.1.в", "tier": "верхнее", "price": 20900},
      {"id": "uyut-b16-2", "roomId": "uyut-r16", "label": "16.2.в", "tier": "верхнее", "price": 20900},
      {"id": "uyut-b16-3", "roomId": "uyut-r16", "label": "16.3.в", "tier": "верхнее", "price": 20900},
      {"id": "uyut-b16-4", "roomId": "uyut-r16", "label": "16.4.в", "tier": "верхнее", "price": 20900},
      {"id": "uyut-b16-5", "roomId": "uyut-r16", "label": "16.5.н", "tier": "нижнее", "price": 24200},
      {"id": "uyut-b16-6", "roomId": "uyut-r16", "label": "16.6.н", "tier": "нижнее", "price": 24200},
      {"id": "uyut-b16-7", "roomId": "uyut-r16", "label": "16.7.н", "tier": "нижнее", "price": 24200},
      {"id": "uyut-b16-8", "roomId": "uyut-r16", "label": "16.8.н", "tier": "нижнее", "price": 24200},
      {"id": "uyut-b17-1", "roomId": "uyut-r17", "label": "17.1.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b17-2", "roomId": "uyut-r17", "label": "17.2.в", "tier": "верхнее", "price": 24200},
      {"id": "uyut-b17-3", "roomId": "uyut-r17", "label": "17.3.н", "tier": "нижнее", "price": 27500},
      {"id": "uyut-b17-4", "roomId": "uyut-r17", "label": "17.4.н", "tier": "нижнее", "price": 27500},
    ]
  },
  {
    id: "molod", name: "Молодежка", title: "Квартира Молодежка", logo: "molodejka.png",
    rooms: [
      {"id": "molod-r1", "buildingId": "molod", "number": "1", "name": "№1 Малая", "gender": "ж", "size": 2, "note": "малая"},
      {"id": "molod-r2", "buildingId": "molod", "number": "2", "name": "№2 Средняя", "gender": "ж", "size": 2, "note": "средняя, места равноценные"},
      {"id": "molod-r3", "buildingId": "molod", "number": "3", "name": "№3 Большая", "gender": "ж", "size": 2, "note": "большая, места равноценные"},
    ],
    beds: [
      {"id": "molod-b1-1", "roomId": "molod-r1", "label": "1.1.н", "tier": "нижнее", "price": 28000},
      {"id": "molod-b1-2", "roomId": "molod-r1", "label": "1.2.в", "tier": "верхнее", "price": 25000},
      {"id": "molod-b2-1", "roomId": "molod-r2", "label": "2.1", "tier": "", "price": 32000},
      {"id": "molod-b2-2", "roomId": "molod-r2", "label": "2.2", "tier": "", "price": 32000},
      {"id": "molod-b3-1", "roomId": "molod-r3", "label": "3.1", "tier": "", "price": 35000},
      {"id": "molod-b3-2", "roomId": "molod-r3", "label": "3.2", "tier": "", "price": 35000},
    ]
  },
];
