(async function(){
 const main=document.querySelector('.page'),me=await fetch('/api/auth/me',{credentials:'same-origin'}).then(r=>r.ok?r.json():null).catch(()=>null);if(!me){main.lastElementChild.innerHTML='Для обращения в поддержку <a href="login.html">войдите в кабинет</a>.';return;}
 const staff=me.role!=='resident',title=main.querySelector('h1'),names={forma:'FORMA',uyut:'Уют на Варшавке',molod:'Молодёжка'};
 while(main.children.length>1)main.lastElementChild.remove();
 const emergency=document.createElement('a');emergency.href='tel:112';emergency.textContent='Экстренные службы — 112';main.append(emergency);
 const select=document.createElement('select');select.className='msv-input';Object.entries(names).forEach(([v,n])=>select.add(new Option(n,v)));if(staff)main.append(select);
 const contact=document.createElement('p'),box=document.createElement('div'),error=document.createElement('p');error.setAttribute('role','alert');main.append(contact,box,error);
 async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined}),j=await r.json();if(!r.ok)throw Error(j.error);return j;}
 function messageForm(parent,path,label){const form=document.createElement('form'),text=document.createElement('textarea'),btn=document.createElement('button');text.className='msv-input';text.required=true;text.maxLength=3000;text.placeholder=label;btn.className='msv-btn msv-btn--primary';btn.textContent='Отправить';form.append(text,btn);form.onsubmit=async e=>{e.preventDefault();btn.disabled=true;try{await api(path,{text:text.value});text.value='';await load();}catch(e){error.textContent=e.message;}finally{btn.disabled=false;}};parent.append(form);}
 if(!staff)messageForm(main,'/api/support','Сообщение куратору или администрации');
 async function load(){try{error.textContent='';const d=await api('/api/support?residence='+select.value);title.textContent='Поддержка'+(d.residence?' · '+names[d.residence]:'');contact.replaceChildren();if(d.contact){contact.append('Куратор: '+d.contact.name+' · ');const tel=document.createElement('a');tel.href='tel:'+d.contact.phone;tel.textContent=d.contact.phone;const tg=document.createElement('a');tg.href='https://t.me/'+d.contact.telegram;tg.textContent='@'+d.contact.telegram;tg.target='_blank';tg.rel='noopener';contact.append(tel,' · ',tg);}else contact.textContent='Куратор пока не назначен. На обращения отвечает администрация.';box.replaceChildren();d.threads.forEach(t=>{const section=document.createElement('section');section.style.cssText='background:white;padding:16px;margin:16px 0;border-radius:12px';const h=document.createElement('h2');h.className='msv-body';h.textContent=t.name+' · '+new Date(t.created_at).toLocaleString('ru-RU');const p=document.createElement('p');p.textContent=t.text;section.append(h,p);t.messages.forEach(m=>{const p=document.createElement('p');p.textContent=(String(m.author_id)===String(t.user_id)?'Резидент: ':'Поддержка: ')+m.text;section.append(p);});messageForm(section,'/api/support/'+t.id+'/reply','Ответ');box.append(section);});if(!d.threads.length)box.textContent='Обращений пока нет.';}catch(e){error.textContent=e.message;}}
 select.onchange=load;load();
})();
